# Generated by Django 4.2 on 2023-04-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=200)),
                ("weight", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("image_url", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Food",
                        to="capstone_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fitness_name", models.CharField(max_length=255)),
                ("duration", models.IntegerField(default=0, null=True)),
                ("img_url", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fitness",
                        to="capstone_app.user",
                    ),
                ),
            ],
        ),
    ]
