# Generated by Django 4.2 on 2023-04-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("capstone_app", "0004_food_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Food",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
